---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argo
  name: external-dns
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: in-cluster
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://kubernetes-sigs.github.io/external-dns
      chart: external-dns
      targetRevision: 1.15.0
      helm:
        valueFiles:
          - $values/apps/system/external-dns/values.yaml
    - repoURL: https://github.com/cseteram/infra.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/cseteram/infra.git
      targetRevision: main
      path: apps/system/external-dns
      directory:
        include: 'resources.yaml'
