---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare
  namespace: external-dns
spec:
  encryptedData:
    CF_API_TOKEN: AgBDENhEf1tppKJ2vjjsqqrgc+75owCu675Yxq6kIL0ePXawf9sYKBgpAPrI1QgJZZsnmkH9Rw3DCprBxvvc+klh+05trxrGK0AA4KJ72yioSlRFxlp5fFJa6cX3uqgtaUDcVqLVxBAsthj9Q3eYMcgW9ZzySUXQ3YEqsLY43ES4mF92Giw7cWJgWpPuAGQEiPAzh1+p4OKhfAkEfR698xHctx304rXKKg90keoC/ZQar1PhIqEv+BxSiYc7spCawFXaqOVw5Aja+S4J2mUvVMw9/P2J8yfw4ZTHdmCDEPuXI2nWPTf9C0lTj3y3wsIumH6NliqlMFUcUMmcVsEDosmXbJmq0XNgGMU61rrtIxUBvNmS7OIMqG/bQK1ohVeFq2/X7sodx4l4+d6DsJNp5+bwmh4GIWq6DRK8jjBiuFb582mk7Jxnh3IuIIVWHUyhs1zyev+0r9i5RekwgR4o/rAL99I+exxukYR+/sLXyYBQ7Dqo9RYPzQmT598LYaQqaKeyvU/Tp9n1753JFHKC5x2YEgOR5h5KaNXgNJNyV466JZmKmKnxrgqLmcIhIX8eEyl3hIhGQEDWjeWOjBl0lKj7m/xvLi390bLaMVBWss+ByyL/ydvhcorSPqdf4xFS9qVkqjY+2u2n7ZMNOn0oo+anTtJjCLYO06o9kzncrXa12x6J2YqRhzT/furERmB+lJFYCOWYtLsJwlSXauIbjgmaJgitiKnsb6epe9RSWchmOIGMVdL0a3UC
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare
      namespace: external-dns
    type: Opaque
