---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgCuVtRvXvvBmZDRM7xG0Fd7UOsr1zhHNjx0pCCLV9WPs5cVeTW2rIL5cjeEFUb7IDUTw52F8Z9F2j9tWRYBv1BWtKAxaM02ADJvJDiywbT/mA+Y2iMrhbS1TyX/KR3I2zaeOx/FaK/3+ImpJ6tb9JtcVO5ptfn8DfbtWm9NhEr0WdN+NWpmnXCZIiP7Vkp0CwQ/QEVdey9UkzHtsAxIEKn56tQ2Bz15B6Zn4NzcN2GWY1Bg/UrMX4aQ92exLedbZ+IKw2QK08L7g1kY8E+BAe3Ljo1i3eare72hdLmUq5As6GE5w+LNFHSxbZca8uOWdl48tSyvudGGAfUlvMjh02szLlBBtAyL/eN41NJbDWx+WStiITNvMJFZZcMk+2A13tni6lANF8BtkEYXu21NqB+jK97fxBCx8Lcx+eMpZ+Jj0YI+hRiKiSvnSZEXDMwM060FxFijbaNB+Ec3TtOv1DapudP1FA5uGGQTiCsJjs0SH1yseUe40JB4MUBPIGs3PaNVXIzJrycHQc1N6vfs46d/C3NGyzo1TaUvhfc+BWt8LuDpGUYVPa2oWe6koiRln0aO411wvWKrFbWGTlXUdLx5dG0RGKCfGlQrbQNhlw4Bgqk8f5Bpopq6PcUgkVcaCCRUwvblNcJi6mwWRMU6vkkvIWtFpUWE2omuTGTlh1YMK/lm7wlpwPpD4193j9vSdcvyJdC6rLkpSOCGw11oOjbvrg==
    client_secret: AgAOXL8h8ymCzw3bVjC0kGzXnMLjI3S/n/hgqbuws8HKULDYycV8PwB8PonDT0BA+auynBLf2stxp0L9ZLUTW4tlv7K9pkHH9gl7DJSdy/WYwhhVI1d4Je/qr4g7zehCHCPPETHYokiMR367ovZ40/C5iQFufTG6HEpdQ+ZzjMX3vMchGy6wQSJiAwpK0ttnpOYJA9fuH5ctopErOnWYX67wls5KqKdoByR6XxFDjonOyPNFYfn+jgarWS5AOyfVS1iVcRO/+SS1/Zf2OgVZfLaXY6tyMInSDC+PYkeNo59R/rNa16XTTcb1MOt24o2IMnsEUtUG5RXvQd6iONY0FawbhuCfpW/03aNPzt5/suli+WRC8dIw0MeRIAk0hjfZlzG2pPYu7vvj3ZGbmOS67rn64mlk3oZw9VTASVWBKAeDKQAKix+hx5xvMJ5vv5TchG1xjwvE6pgAweDgevCnK5eZZUfD1OlJxRbN+VQQfM88V+AhGCxoFLb0GfVPssXEXZBmqG5XalGE/yQshBktgbrpYsqpu0f2q+2pG2nGKnabc/jX26AyYdvJ6o7IeLAer0OUyNDiG8myalFrd03ovxzb/5gHHwnE28aADEEQj0rsOggavLVSNcImXl1zM0GHgz5W5U6RrXkqS67vtNfp1NYfvyX3C5oWqdeDqj1QWnZEO6blC+r1s8q2WKoaTFSctdO8jUK4IagLTEEw50Wl5xkshCPhvH/CzvoeG2SKiRjYTJxhKby0KzxppcAYbgzNhlzwH9C95h3A5NGAqr4TMcU=
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
---
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: ts-sekai
spec:
  hostname: ts-sekai
  exitNode: true
