---
apiVersion: v1
kind: Namespace
metadata:
  name: test-nic
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-nic
  namespace: test-nic
spec:
  replicas: 5
  selector:
    matchLabels:
      app: test-nic
  template:
    metadata:
      labels:
        app: test-nic
    spec:
      containers:
      - name: nginx
        image: luksa/kubia:latest
---
apiVersion: v1
kind: Service
metadata:
  name: test-nic
  namespace: test-nic
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: test-nic
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-nic
  namespace: test-nic
spec:
  ingressClassName: nginx
  rules:
  - host: test-nic.cseteram.dev
    http:
      paths:
      - backend:
          service:
            name: test-nic
            port:
              number: 80
        path: /
        pathType: Prefix
