apiVersion: v1
kind: Namespace
metadata:
  name: test-pvc
---
apiVersion: v1
kind: Pod
metadata:
  name: app
  namespace: test-pvc
spec:
  containers:
  - name: app
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace: test-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
