---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argo
  name: root
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: in-cluster
    namespace: argo
  source:
    repoURL: https://github.com/cseteram/infra.git
    targetRevision: main
    path: apps
    directory:
      recurse: true
      include: '{*/application.yml,*/application.yaml}'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
