server:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
    - argo.cseteram.dev

configs:
  cm:
    url: https://argo.cseteram.dev
    admin.enabled: false
    dex.config: |
      connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: 9ef85bdbf5d08f4518db
          clientSecret: $github-oauth:dex.github.clientSecret
  
  params:
    server.insecure: true

  rbac:
    policy.csv: |
      g, cseteram.dev@gmail.com, role:admin
    scopes: "[email]"
