alertmanager:
  enabled: false

prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi

grafana:
  imageRenderer:
    grafanaProtocol: https
  
  grafana.ini:
    server:
      domain: dashboard.cseteram.dev
      root_url: "https://%(domain)s"

  persistence:
    enabled: true
    type: pvc
    size: 4Gi

  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
    - dashboard.cseteram.dev
