alertmanager:
  enabled: false

prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 16Gi

grafana:
  imageRenderer:
    grafanaProtocol: https
  
  grafana.ini:
    server:
      domain: dashboard.cseteram.dev
      root_url: "https://%(domain)s"
    auth.github:
      enabled: true
      allow_sign_up: true
      scopes: user:email
      auth_url: https://github.com/login/oauth/authorize
      token_url: https://github.com/login/oauth/access_token
      api_url: https://api.github.com/user
      client_id: '011d7c4bd301eebb7a44'
      client_secret: '$__file{/etc/secrets/github-oauth/secret}'

  extraSecretMounts:
  - name: github-oauth-mount
    secretName: github-oauth
    defaultMode: 0440
    mountPath: /etc/secrets/github-oauth
    readOnly: true

  persistence:
    enabled: true
    type: pvc
    size: 8Gi

  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
    - dashboard.cseteram.dev
